### ISSUE TITLE
Password Issue

### ISSUE THREAD

**Issue by The-Rock-21** [monkey3three/unblocked88.github.io#6]
**Describe the bug**
Don't need password to enter

**To Reproduce**
1. Go to site
2. When it asks for a password, click ok and click on another tab and wait a while
3. When it looks like it has stopped loading, click back to the site. 
4. Click ok and no password needed

**Expected behavior**
When the site opens, it asks for a password. When you don't know and just click ok, it says incorrect password. When you click off the tab and go back to the tab, it should still be loading because correct password hasn't been entered yet.

**Screenshots**

Chromebook

**Additional context**

**Comment by monkey3three** [comment]
The password is for my school, as people were going to get it banned so I added a password for me and my friends to use. Someone did figure this out at my school, but I don't think they know how to replicate it. I don't remember what they did but they didn't mention anything because switching tabs. I might fix this in a bit, but it's not important for me right now. Tell me if you think I should fix this soon, but I don't think so.

**Comment by monkey3three** [comment]
I've found a solution. 
This code works as when you go out of the tab for a while it just closes the alert not letting you in. When it is correct, it will redirect. Will include in update tommorow.
<html>
<body>
<div class="line alt1" style="box-sizing: border-box; margin: 0px !important; padding: 0px !important; border: 0px !important; outline: 0px !important; background: 0px 0px rgb(15, 25, 42) !important; text-align: left; float: none !important; vertical-align: baseline !important; position: static !important; inset: auto !important; height: auto !important; width: auto !important; line-height: 1.1em !important; font-family: consolas, &quot;bitstream vera sans mono&quot;, &quot;courier new&quot;, Courier, monospace; font-weight: 400; font-style: normal; font-size: 17px; direction: ltr !important; color: rgb(113, 128, 150); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

<script type="text/javascript">
--


</div>
</body>
</html>
